const express = require('express');
const { authMiddleware, authorizationMiddleware } = require('../../../shared/middleware');

function parsePagination(query) {
  const page = Math.max(1, parseInt(query.page || 1));
  const limit = Math.max(1, Math.min(100, parseInt(query.limit || 10)));
  return { page, limit, offset: (page - 1) * limit };
}

function filterWritableFields(model, body) {
  const data = {};
  for (const [field, value] of Object.entries(body || {})) {
    const attr = model.rawAttributes[field];
    if (!attr || attr.primaryKey || attr._autoGenerated) continue;
    if (field === 'creado_en' || field === 'created_at' || field === 'updated_at') continue;
    data[field] = value;
  }
  return data;
}

function buildWhere(query, allowedFilters) {
  const where = {};
  for (const filter of allowedFilters) {
    if (query[filter] !== undefined && query[filter] !== '') {
      where[filter] = query[filter];
    }
  }
  return where;
}

function createCrudRouter(options) {
  const {
    model,
    include = [],
    order = [['id', 'DESC']],
    allowedFilters = [],
    readOnly = false,
    adminOnlyWrites = true
  } = options;

  const router = express.Router();
  const writeMiddlewares = adminOnlyWrites ? [authorizationMiddleware(1)] : [];

  router.get('/', authMiddleware, async (req, res, next) => {
    try {
      const { page, limit, offset } = parsePagination(req.query);
      const where = buildWhere(req.query, allowedFilters);
      const { count, rows } = await model.findAndCountAll({
        where,
        include,
        order,
        offset,
        limit
      });

      res.json({
        success: true,
        data: rows,
        pagination: {
          page,
          limit,
          total: count,
          pages: Math.ceil(count / limit),
          hasMore: offset + limit < count
        },
        timestamp: new Date().toISOString()
      });
    } catch (error) {
      next(error);
    }
  });

  router.get('/:id', authMiddleware, async (req, res, next) => {
    try {
      const item = await model.findByPk(req.params.id, { include });
      if (!item) {
        return res.status(404).json({
          success: false,
          error: { code: 'NOT_FOUND', message: 'Registro no encontrado' },
          timestamp: new Date().toISOString()
        });
      }
      res.json({ success: true, data: item, timestamp: new Date().toISOString() });
    } catch (error) {
      next(error);
    }
  });

  if (!readOnly) {
    router.post('/', authMiddleware, ...writeMiddlewares, async (req, res, next) => {
      try {
        const item = await model.create(filterWritableFields(model, req.body));
        res.status(201).json({ success: true, data: item, timestamp: new Date().toISOString() });
      } catch (error) {
        next(error);
      }
    });

    router.put('/:id', authMiddleware, ...writeMiddlewares, async (req, res, next) => {
      try {
        const item = await model.findByPk(req.params.id);
        if (!item) {
          return res.status(404).json({
            success: false,
            error: { code: 'NOT_FOUND', message: 'Registro no encontrado' },
            timestamp: new Date().toISOString()
          });
        }
        await item.update(filterWritableFields(model, req.body));
        res.json({ success: true, data: item, timestamp: new Date().toISOString() });
      } catch (error) {
        next(error);
      }
    });

    router.delete('/:id', authMiddleware, ...writeMiddlewares, async (req, res, next) => {
      try {
        const item = await model.findByPk(req.params.id);
        if (!item) {
          return res.status(404).json({
            success: false,
            error: { code: 'NOT_FOUND', message: 'Registro no encontrado' },
            timestamp: new Date().toISOString()
          });
        }
        await item.destroy();
        res.json({ success: true, message: 'Registro eliminado', timestamp: new Date().toISOString() });
      } catch (error) {
        next(error);
      }
    });
  }

  return router;
}

module.exports = createCrudRouter;
