// Shared Enums and Constants

const ROLES = {
  ADMIN: 1,
  TRABAJADOR: 2,
  SUPERVISOR: 3
};

const ROLE_NAMES = {
  1: 'ADMIN',
  2: 'TRABAJADOR',
  3: 'SUPERVISOR'
};

const JORNADA_STATES = {
  ACTIVA: 'ACTIVA',
  CERRADA: 'CERRADA',
  CANCELADA: 'CANCELADA'
};

const VEHICLE_STATES = {
  OPERATIVO: 'OPERATIVO',
  TALLER: 'TALLER',
  FALLA: 'FALLA'
};

const AVERIA_GRAVEDAD = {
  BAJA: 'BAJA',
  MEDIA: 'MEDIA',
  ALTA: 'ALTA',
  CRITICA: 'CRITICA'
};

const CHECKLIST_ITEMS = {
  COMBUSTIBLE: 'COMBUSTIBLE',
  ACEITE: 'ACEITE',
  LLANTAS: 'LLANTAS',
  FRENOS: 'FRENOS',
  LUCES: 'LUCES',
  LIMPIADORES: 'LIMPIADORES',
  ESPEJOS: 'ESPEJOS'
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500
};

module.exports = {
  ROLES,
  ROLE_NAMES,
  JORNADA_STATES,
  VEHICLE_STATES,
  AVERIA_GRAVEDAD,
  CHECKLIST_ITEMS,
  HTTP_STATUS
};
